WITH bookings AS (
    SELECT 
    BOOKING_ID,
    BOOKING_DATE,
    BOOKING_STATUS,
    CREATED_AT
    FROM {{ref("obt")}}
    GROUP BY BOOKING_ID,
    BOOKING_DATE,
    BOOKING_STATUS,
    CREATED_AT
)
SELECT * FROM bookings