WITH LISTINGS AS (
    SELECT
    LISTING_ID,
    PROPERTY_TYPE,
    ROOM_TYPE,
    CITY,
    COUNTRY,
    PRICE_PER_NIGHT_TAG,
    LISTINGS_CREATED_AT
    FROM {{ref('obt')}}
    GROUP BY LISTING_ID,
    PROPERTY_TYPE,
    ROOM_TYPE,
    CITY,
    COUNTRY,
    PRICE_PER_NIGHT_TAG,
    LISTINGS_CREATED_AT
)

SELECT * FROM LISTINGS